---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}

library(tidyverse)
library(terra)
library(sf)
library(mgcv)
library(tmap)
library(here)
library(parallel)

knitr::opts_chunk$set(echo = TRUE)

nc <- 3 # number of cores
cl <- makeCluster(nc)
```

This script generates figures showing the relative distribution of human and
livestock populations across different climatic and environmental mean
conditions.

```{r load}

# Africa country boundaries (Natural Earth dataset)
countries <- st_read(here("data", "raw_data", "vector", "natural_earth",
                          "ne_110m_admin_0_countries_fixed.shp"))
africa <- filter(countries, CONTINENT == "Africa")
africa_vct <- vect(africa)

# PML_V2 multi-annual mean GPP values 
# Convert GPP to raw units (scale by 0.01)
gpp_mean <- rast(here("data", "raw_data", "raster", "main_variables",
                      "pmlv2_gpp_mean.tif")) * 0.01

# CHIRPS precipitation variables
map <- rast(here("data", "raw_data", "raster", "main_variables",
                 "chirps_MAP.tif"))
cv <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_annual_CV.tif"))
intensity <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_intensity.tif"))
dry <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_dry_days.tif"))
ugi <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_UGi.tif"))
pci <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_PCI.tif"))
pc_95 <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_95pc.tif"))
wet_95 <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_wet_95pc.tif"))
gt10 <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_exceed_10.tif"))
gt20 <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_exceed_20.tif"))
gt30 <- rast(here("data", "raw_data", "raster", "main_variables",
                "chirps_exceed_30.tif"))

# CHIRPS season length and onset data 
season_length <- rast(here("data", "raw_data", "raster", "season_variables",
                           "season_length_all.tif"))
season_length_sd <- rast(here("data", "processed_data", "raster",
                              "season_length_sd.tif"))
season_onset_sd <- rast(here("data", "processed_data", "raster",
                             "season_onset_sd.tif"))

# ERA5-Land mean air temperature
meanT <- rast(here("data", "raw_data", "raster", "main_variables", "era5_T.tif"))

meanT_resample <- disagg(meanT, 2, method = "bilinear")

# MODIS mean daytime land surface temperature
lst <- rast(here("data", "raw_data", "raster", "main_variables", "modis_lst.tif"))

# MODIS fire frequency 2001-2019
fire <- rast(here("data", "raw_data", "raster", "main_variables", "modis_burn_freq.tif")) %>%
  classify(matrix(c(NA, 0), nrow = 1))

# iSDAsoil data (top 20cm)
soil <- rast(here("data", "raw_data", "raster", "main_variables", "isda_0_20_cm.tif")) %>%
  crop(map) # Fixing error in extent from export
names(soil) <- c("sand", "clay", "N", "P")

# Mask layers
# Aridity index
ai <- rast(here("data", "raw_data", "raster", "study_area_masks",
                "aridity.tif"))

# MODIS land cover classification IGBP
igbp <- rast(here("data", "raw_data", "raster", "study_area_masks",
                  "IGBP_land_cover.tif"))

# ESA WorldCover 10m land cover masks (2020)
# Additional higher-resolution layers excluding urban, cropland and forested land
esa_other <- rast(here("data", "raw_data", "raster", "study_area_masks",
                  "esa_lc_frac.tif"))
esa_tree <- rast(here("data", "raw_data", "raster", "study_area_masks",
                  "esa_tree_frac.tif"))

# Zero mask (remove pixels where more than 25% of sub-pixels are zero for all
# years in the dataset)
zero_mask <- rast(here("data", "raw_data", "raster", "study_area_masks",
                       "pmlv2_zero_mask.tif"))

# Load ruminant population data

cattle <- rast(here("data", "raw_data", "raster", "population",
                    "6_Ct_2015_Aw.tif"))
sheep <- rast(here("data", "raw_data", "raster", "population",
                    "6_Sh_2015_Aw.tif"))
goat <- rast(here("data", "raw_data", "raster", "population",
                    "6_Gt_2015_Aw.tif"))
area <- rast(here("data", "raw_data", "raster", "population",
                    "8_Areakm.tif"))

livestock_dens = c(cattle, sheep, goat) / area

# Human population data
pop_dens <- rast(here("data", "raw_data", "raster", "population",
                    "gpw_v4_population_density_rev11_2015_2pt5_min.tif"))

```
Clip, mask and pre-process data layers:

```{r mask, include = FALSE}

igbp_index <- tibble(lc = c(6, 7, 8, 9, 10),
                     cover = factor(c("Closed shrublands",
                                      "Open shrublands",
                                      "Woody savannas",
                                      "Open savannas",
                                      "Grasslands")))

# Mask IGBP layers to African continental boundaries
igbp_mask <- mask(igbp, africa_vct)

# Most common assigned IGBP class

# getMode <- function(x) {
# keys <- na.omit(unique(x))
# keys[which.max(tabulate(match(x, keys)))]
# }
# 
# igbp_mode <- app(igbp_mask, getMode)
# 
# # Write and read modal IGBP class layer (slow to calculate)
# writeRaster(igbp_mode, here("data", "processed_data", "raster",
#                             "igbp_mode.tif"),
#             overwrite = TRUE)

igbp_mode <- rast(here("data", "processed_data", "raster",
                       "igbp_mode.tif"))

# Aridity index mask (include areas with 0.05 < ai > 0.65)
ai_mask <- (ai > 500 & ai < 6500)

# ESA masks (exclude > 25% non-rangeland or > 50% tree cover)
esa_mask <- (esa_other < 0.25) & (esa_tree < 0.5)

# Combine masks
study_area_mask <- igbp_mode & ai_mask & esa_mask & zero_mask

# Study area mask function
sa_mask <- function(spatRaster) {
  masked <- spatRaster %>%
    mask(study_area_mask, maskvalues = c(0, NA))
  
  masked
}

# Reproject population rasters and crop/mask to the same area as other data

livestock_chirps <- project(livestock_dens, var_stack)
pop_chirps <- project(pop_dens, var_stack)

all_pop <- c(livestock_chirps, pop_chirps) %>% sa_mask()

all_pop
tm_shape(all_pop) + tm_raster(breaks = c(0, 10, 50, 100, 500, 1000, 5000))

# Create stack of covariate rasters and mask to study region

var_stack <- c(igbp_mode,
               gpp_mean,
               soil, fire, meanT_resample, lst,
               map, cv, intensity, dry, ugi, pc_95, wet_95,
               gt10, gt20, gt30,
               pci, season_length, season_length_sd, season_onset_sd,
               all_pop)

names(var_stack) <- c("lc",
                      "gpp",
                      "sand", "clay", "soilN", "soilP",
                      "fire", "meanT", "lst_mean",
                      "map", "cv", "intensity", "dry_days", "ugi",
                      "pc95", "wet95",
                      "gt10", "gt20", "gt30",
                      "pci", "season", "season_sd", "onset_sd",
                      "cattle", "sheep", "goat", "pop_dens")

var_stack_masked <- sa_mask(var_stack)


```

Convert whole raster to data frame

```{r to_df, cache = F, dependson = c("load", "mask"), include = FALSE}

df <- as.data.frame(var_stack_masked, xy = TRUE) %>%
  left_join(igbp_index)

```
```{r plots}

plot_vars <- c("map", "cv", "intensity", "ugi", "wet95", "season", "onset_sd",
               "meanT", "lst_mean", "sand", "soilN", "fire")

df %>%
  select(plot_vars, c("cattle", "sheep", "goat", "pop_dens")) %>%
  pivot_longer(cols = c(cattle, goat, sheep, pop_dens),
               names_to = "animal", values_to = "population") %>%
  pivot_longer(cols = plot_vars,
               names_to = "var", values_to = "value") %>%
  ggplot(aes(x = value, y = population, colour = animal)) +
  geom_smooth() +
  facet_wrap(~var, scales = "free")

ggplot(df, aes(x = cv, y = goat)) + geom_smooth()



```


```{r pop_gams}

fit_gam <- function(df) {
  mod <- gam(population ~ s(map, bs = "ts") + s(cv, bs = "ts") + s(intensity, bs = "ts") + 
               s(ugi, bs = "ts") + s(wet95, bs = "ts") +
               s(season, bs = "ts") + s(onset_sd, bs = "ts") +
               s(meanT, bs = "ts") + s(lst_mean, bs = "ts") + s(sand, bs = "ts") + s(fire, bs = "ts") +
               te(x, y, k = c(8, 8), bs = "ts"),
             data = df,
             family = gaussian(link = "log"),
             cluster = cl)
  
  mod
}


Sys.time()
set.seed(999)
pop_gams <- df %>%
  slice_sample(prop = 0.05) %>%
  pivot_longer(cols = c(cattle, goat, sheep, pop_dens),
               names_to = "animal", values_to = "population") %>%
  select(plot_vars, animal, population, x, y) %>%
  group_by(animal) %>%
  mutate(population = population + 0.001) %>%
  nest() %>%
  mutate(mod = map(data, fit_gam))
Sys.time()

pop_gams %>%
  mutate(glance = map(mod, broom::glance)) %>%
  unnest(glance)

plot(pop_gams$mod[[3]])

saveRDS(pop_gams, here("data", "processed_data", "models", "pop_models.rds"))

```

